### ISSUE TITLE
When will you release the code for the dataset ? Thank you!

### ISSUE THREAD

**Issue by shuluoshu** [xheon/panoptic-reconstruction#1]
@xheon  Hi, nice work, I want to follow your work and use your generated dataset, when will you release the code and dataset?

**Comment by xheon** [comment]
Hi, thanks a lot!

we are cleaning up the code for training as well as for data generation currently. 
We are also checking the licenses of the original datasets, if we can directly release the generated data.
Code will be ready within few days :)

**Comment by xheon** [comment]
Please check the latest commits for the model and training code.
The dataset code will follow soon as well :)
