### ISSUE TITLE
Link Download issue

### ISSUE THREAD

**Issue by wenyihan4396** [xheon/panoptic-reconstruction#14]
Hi. I wanted to download the model from link in Table, but I can not open the .pth file's link in Table.
Could you please be kind to update the link?

**Comment by wenyihan4396** [comment]
Sorry to interrupt
I exchange browser to firefox and successfully download it.

**Comment by xheon** [comment]
Hi, i updated the links to use HTTPS instead of HTTP, which was blocked by github.
