### ISSUE TITLE
About 2D PRETRAIN

### ISSUE THREAD

**Issue by happysxpp** [xheon/panoptic-reconstruction#15]
Excuse me, where can I find the 2D pre training model?

or, how can I train my 2D model myself?

In front3d_train_3d.yaml, 

```
MODEL:
    FIX2D: True
    PRETRAIN: "/cluster_HDD/gondor/mdahnert/panoptic-release/front3d-mask_depth_r18.pth"
```

I'd appreciate it if you could provide some idea on this problem. Thank you!

**Comment by xheon** [comment]
Hi, thanks for letting me know. I added the link to the download table in the readme.
The 2D model actually also is part of the pretrained 3D network.
