### ISSUE TITLE
Visualizing output generated by the network

### ISSUE THREAD

**Issue by ajonnavittula** [xheon/panoptic-reconstruction#18]
Thank you for sharing your awesome code. I loved the images generated by you in your paper. Do you happen to have any code that I can use to create similar pictures using the .ply files generated by the network?

**Comment by xheon** [comment]
Hi, thanks a lot!
The images in the result figure Fig. 4 were generated manually using Blender by importing the ply, placing some light sources and render it from a certain view point with the Cycles renderer.

The results in Fig 5. are from MeshLab.
