### ISSUE TITLE
Timelines for releasing code for the model?

### ISSUE THREAD

**Issue by Jerrypiglet** [xheon/panoptic-reconstruction#2]
Hi there, thanks for putting the effort on the code release! I wonder if there is a timeline for when the code will be ready?

**Comment by xheon** [comment]
Hi, please check the latest commits :)
There are some minor to-dos left, which will follow soon as well.

**Comment by Jerrypiglet** [comment]
> Hi, please check the latest commits :) There are some minor to-dos left, which will follow soon as well.

hey there, thanks a lot for the update! I just checked the repo and was wondering if there are any instructions on how to use the code (./lib/*) for training and inference? A demo script for training would be very helpful.
