### ISSUE TITLE
Configs Provided are for training 3D network

### ISSUE THREAD

**Issue by unlugi** [xheon/panoptic-reconstruction#20]
Dear Author,

The config file you provided 'front3d_train_3d.yaml' is for training the 3D network only.
Can you please share full pipeline training configs? Both 2D networks and 3D networks?

**Comment by xheon** [comment]
Hi,

I just pushed the configuration for the 2D part. 
Please note, we don't train both parts (2D & 3D) together. We first train the 2D part only, then freeze it and train the 3D part.
We tried it, but it didn't improve the model - but feel free to try :)
