### ISSUE TITLE
cannot use the code

### ISSUE THREAD

**Issue by gilbert248** [xheon/panoptic-reconstruction#25]
my conda environment is: cuda11.1+pytorch1.9.0,
when running this command: python tesr_net_single_image_.py
it occurs the error: RuntimeError： expected all tensors to be on the same device, but found at least two device, cuda:0 and cpu!
but i took a look at the test_net_single_image.py, there may be nothing wrong with the code, i don't know how to solve it, i will be very appreciated if any one could help me.

**Comment by xheon** [comment]
Hi, could you post the complete error message, especially the line where the error occurs?

**Comment by ZhiyaoZhou** [comment]
thank you for your reply! the error shows in screenshot as below:
![Cache_768ae03537a5ac8d](https://github.com/xheon/panoptic-reconstruction/assets/141822008/6e9c7944-9726-4643-8491-9abe6dc47f01)
it seems like there maybe not all the tensors have passed to cuda which i used(i use single RTX 3090 card).
to check if there exits any tensors that haven't been 
pass to cuda, i added some code in the /panoptic-reconstruction/lib/modeling/frustum/post_process.py for checkout(according to the error occured):
```python
print(instances_filtered.type())
print(instance_id.type())
``` 
and it returns in the terminal:
```python
torch.cuda.LongTensor
torch.LongTensor
```
so the variable instance_id was not passed to cuda,
and i did some changes to the code in  /panoptic-reconstruction/lib/modeling/frustum/post_process.py :
![Cache_59390c12f9ddb657](https://github.com/xheon/panoptic-reconstruction/assets/141822008/2fea9144-34a4-4671-8473-ee77a5df0dfb)
the code lines drawed with red line is added by me, and run the command again and it works:
![Cache_283c7c9b9ec92901](https://github.com/xheon/panoptic-reconstruction/assets/141822008/69175fd8-6f2c-413e-904d-c49c35ec936b)
i don't know if its appropriate to change the code like that, maybe there has a better way to improve it.

**Comment by gilbert248** [comment]
thank you for your reply! the error shows in screenshot as below:
![Cache_768ae03537a5ac8d](https://github.com/xheon/panoptic-reconstruction/assets/141822008/6e9c7944-9726-4643-8491-9abe6dc47f01)
it seems like there maybe not all the tensors have passed to cuda which i used(i use single RTX 3090 card).
to check if there exits any tensors that haven't been 
pass to cuda, i added some code in the /panoptic-reconstruction/lib/modeling/frustum/post_process.py for checkout(according to the error occured):
```python
print(instances_filtered.type())
print(instance_id.type())
``` 
and it returns in the terminal:
```python
torch.cuda.LongTensor
torch.LongTensor
```
so the variable instance_id was not passed to cuda,
and i did some changes to the code in  /panoptic-reconstruction/lib/modeling/frustum/post_process.py :
![Cache_59390c12f9ddb657](https://github.com/xheon/panoptic-reconstruction/assets/141822008/2fea9144-34a4-4671-8473-ee77a5df0dfb)
the code lines drawed with red line is added by me, and run the command again and it works:
![Cache_283c7c9b9ec92901](https://github.com/xheon/panoptic-reconstruction/assets/141822008/69175fd8-6f2c-413e-904d-c49c35ec936b)
i don't know if its appropriate to change the code like that, maybe there has a better way to improve it.
