### ISSUE TITLE
Front3D dataset required

### ISSUE THREAD

**Issue by ywcmaike** [xheon/panoptic-reconstruction#3]
Hi Manuel, I'm interested in your recent work "Panoptic 3D Scene Reconstruction from a Single RGB Image", and want to try your released code. However, I cannot find the exact file in the code, such as "**resources/front3d/train_list_2d.txt**". I know maybe the dataset is big, could you provide me with the processed dataset link in dropbox or google drive or the preprocessed code as your paper said?  I'm looking forward to your reply. Thanks a lot.
@xheon

**Comment by xheon** [comment]
Hi, thanks for your message. Please check the latest commits for the sample file lists.

You can find the data set here: https://hidrive.ionos.com/share/nfgac71bo2
Please note, that it's a temporary location of the data and I might have to move the data (in that case, I will update the link).

Also note, according to the Terms of Use of 3D-Front, only non-commercial, scientific research usage is allowed.
By downloading our derivative works of 3D-Front, you agree to NOT use it for commercial purposes: [3D-Front Terms of Use](https://gw.alicdn.com/bao/uploaded/TB1ZJUfK.z1gK0jSZLeXXb9kVXa.pdf?spm=a1z3i.a4.0.0.3f5beb1digOegr&file=TB1ZJUfK.z1gK0jSZLeXXb9kVXa.pdf)
