### ISSUE TITLE
panoptic_front3d.pth

### ISSUE THREAD

**Issue by WarmRoseX** [xheon/panoptic-reconstruction#4]
Hi Manuel,I'm a freshman who just started running code recently and interested in your recent work "Panoptic 3D Scene Reconstruction from a Single RGB Image", and want to try your released code. However, I cannot find the exact pretrain model , such as "panoptic_front3d.pth". Could you provide me with the pretrain model link in google drive or baidu cloud? I'm looking forward to your reply. Thanks a lot. @xheon

**Comment by xheon** [comment]
Hi, thanks for your message. 

You can find the data set and a pretrained model here: https://hidrive.ionos.com/share/nfgac71bo2
Please note, that it's a temporary location of the data and I might have to move the data (in that case, I will update the link).

Also note, according to the Terms of Use of 3D-Front, only non-commercial, scientific research usage is allowed.
By downloading our derivative works of 3D-Front, you agree to NOT use it for commercial purposes: [3D-Front Terms of Use](https://gw.alicdn.com/bao/uploaded/TB1ZJUfK.z1gK0jSZLeXXb9kVXa.pdf?spm=a1z3i.a4.0.0.3f5beb1digOegr&file=TB1ZJUfK.z1gK0jSZLeXXb9kVXa.pdf)

Feel free to re-open this issue or create a new one, if you have further questions.
