### ISSUE TITLE
Missing function in sparse projection module

### ISSUE THREAD

**Issue by chriswxho** [xheon/panoptic-reconstruction#5]
In `lib/modeling/projection/sparse_projection.py` line 38, there is a function `self.compute_camera2frustum_transform` that is called, but there is no corresponding function within the class definition. Is there somewhere else I can find this code in the repo?

edit - is this function intended to compute the extrinsic matrix?

**Comment by xheon** [comment]
Hi, please check the latest commits. there was an issue with git, so a bigger commit wasn't pushed to GitHub - sorry for that...
