### ISSUE TITLE
Tool for data generation

### ISSUE THREAD

**Issue by nicolaihaeni** [xheon/panoptic-reconstruction#7]
Hi

I was wondering if you could release the code for the generation of the unsigned distance field to try your repository on new datasets?

Thank you

**Comment by xheon** [comment]
Hi,

I haven't had time to clean up the 3D data generation code yet. 

To give some context:
It builds on SDFGen (https://github.com/christopherbatty/SDFGen) and mLib (https://github.com/niessner/mLib) and is cross-compiled from Windows to run on Linux.

If it's urgent, you can write an email (manuel.dahnert@tum.de) and I can provide you with a copy of the current, un-cleaned code.

**Comment by zoey-shan** [comment]
Hi

I also met some problems on generating the 3D data. And I wonder if the code for the generation of the unsigned distance field is available to release now? Or can I also email you for a copy?

Thank you

**Comment by xheon** [comment]
I replied to your email :)
